### ISSUE TITLE
[Question] Access remote app

### ISSUE THREAD

**Issue by ggros-septeo** [vugar005/youtube-webapp-turborepo#59]
Hi Vugar,

I've found your repo through an article on Medium. Great work you have done there. Thanks for sharing this.

I have one question tough, the shell app is running fine but how can I access a remote app "independently" ? When I navigate for example to http://localhost:4203 (which is the Like app) nothing is displaying. I tried http://localhost:4203 and http://localhost:4203/liked.

Thank you

![image](https://github.com/vugar005/youtube-webapp-turborepo/assets/134306187/ffdee7dc-eed9-4dd1-b428-8667e0d1c6de)

**Comment by vugar005** [comment]
HI @ggros-septeo 
The reason the remote app is not bootstrap is because it is web-component(angular element) which is intended to be use in Shell app. 
But you can achieve bootstrapping this app by
**1**- Changing bootstrap config to be compiled as app instead of web component (angular element).
```
// (async function () {
//   const envInjector = await createApplication(config);
//   const ce = createCustomElement(AppComponent, { injector: envInjector.injector });
//   customElements.define('likes-app-element', ce);
// })();

/* For running app seperately without shell */
 bootstrapApplication(AppComponent, config).catch((err) => console.error(err));
```
**2**- Import styles and index.html (because remote apps get it from shell).
I already improved this in latest PR. You don't need to configure this but nice to know.

**3**- Navigate to : ``` http://localhost:4202/liked ```

**Comment by ggros-septeo** [comment]
Thank you for your answer. Much appreciated.
